### ISSUE TITLE
Posts with Attachments

### ISSUE THREAD

**Issue by Redstoneguy129** [IATkachenko/patreon-post#1]
Can this be made to also post our releases?

**Comment by IATkachenko** [comment]
[Redstoneguy129](https://github.com/Redstoneguy129), hello.

Fell free to use it for your project! But, this action simulate browser requests to Patreon (because it have no public AIP) and very unstable. I can't guarantee anything.
Also I'm not using it now, so developing is frozen (but python code is very simple and PR are welcomed).
